import { Injectable, Logger } from '@nestjs/common';
import {
  ProviderAdapter,
  ProviderEventInput,
  KnowledgeItem,
  EyeType,
  Provider,
} from '../contracts';

/**
 * Slack-specific implementation of ProviderAdapter.
 *
 * Normalizes raw Slack Event API payloads into KnowledgeItems.
 *
 * Currently a minimal placeholder — will be expanded when Event Subscriptions
 * are configured in the Slack App to handle message.channels, etc.
 */
@Injectable()
export class SlackAdapterService implements ProviderAdapter {
  private readonly logger = new Logger(SlackAdapterService.name);

  /**
   * Normalizes a raw Slack event_callback payload into KnowledgeItem(s).
   *
   * For now, handles `message` events in channels.
   * Returns [] for any event type we don't handle yet.
   */
  normalizeEvent(input: ProviderEventInput): KnowledgeItem[] {
    const payload = input.rawPayload as any;

    let event: any;

    // Slack Events API wraps events inside an 'event' envelope:
    // { type: 'event_callback', event: { type: 'message', channel: 'C123', ... } }
    if (payload.type === 'event_callback' && payload.event) {
      event = payload.event;
    } 
    // Slack Web API (conversations.history) returns messages directly
    else if (payload.type === 'message') {
      event = payload;
    } 
    else {
      this.logger.debug(`Ignoring unhandled payload type: ${payload.type}`);
      return [];
    }

    // Only handle 'message' events for now
    if (event.type !== 'message' || event.subtype) {
      this.logger.debug(
        `Ignoring event type: ${event.type}, subtype: ${event.subtype}`,
      );
      return [];
    }

    return [
      {
        id: undefined as any, // Auto-generated by DB
        organizationId: input.organizationId,
        eyeType: EyeType.CHAT,
        provider: Provider.SLACK,
        sourceType: 'channel_message',
        eventType: 'message',
        externalResourceId: event.channel,
        externalEventId: event.ts, // Slack's unique message timestamp
        parentExternalResourceId: event.thread_ts || null,
        title: null,
        content: event.text || '',
        author: {
          externalId: event.user,
        },
        participants: event.user ? [{ externalId: event.user }] : [],
        contextLocation: `Slack Channel ${event.channel}`,
        sourceUrl: `https://slack.com/archives/${event.channel}/p${(event.ts || '').replace('.', '')}`,
        occurredAt: new Date(parseFloat(event.ts) * 1000),
        receivedAt: new Date(),
        visibility: 'ORGANIZATION',
        metadata: {
          team_id: payload.team_id,
          event_id: payload.event_id,
        },
        rawPayloadReference: input.rawEventReference,
        version: null,
      },
    ];
  }

  /**
   * Generates a globally unique idempotency key for a Slack message.
   * A Slack message is uniquely identified by channel + timestamp.
   */
  getIdempotencyKey(item: KnowledgeItem): string {
    return `slack:${item.organizationId}:${item.externalResourceId}:${item.externalEventId}`;
  }

  /**
   * Extracts the channel ID from the raw payload.
   */
  getExternalResourceId(input: ProviderEventInput): string {
    const payload = input.rawPayload as any;
    const event = payload?.event || payload;
    return event?.channel || 'unknown';
  }

  /**
   * Extracts the message timestamp from the raw payload.
   */
  getExternalEventId(input: ProviderEventInput): string | null {
    const payload = input.rawPayload as any;
    const event = payload?.event || payload;
    return event?.ts || null;
  }
}
